DATAS SEGMENT
    DATA1 DB 'HELLO $'
    LEN1 EQU  $-DATA1-1
    DATA2 DB 'WORLD$'
    LEN2 EQU  $-DATA2
    DATA3 DB 20 DUP(11H)  
DATAS ENDS

STACKS SEGMENT
    ;此处输入堆栈段代码
STACKS ENDS

CODES SEGMENT
    ASSUME CS:CODES,DS:DATAS,SS:STACKS
START:
    MOV AX,DATAS
    MOV DS,AX
    MOV ES,AX
    
    LEA SI,DATA1
    LEA DI,DATA3
    
    MOV CX,LEN1
    REP MOVSB
    
    LEA SI,DATA2
    
    MOV CX,LEN2
    REP MOVSB
    
    MOV AH,4CH
    INT 21H
CODES ENDS
    END START