/****3.1****/
/*CREATE DATABASE [SPJ]
GO

USE SPJ
GO

CREATE TABLE S
(
    SNO CHAR(2) PRIMARY KEY,
    SNAME CHAR(10),
    STATUS_ INT,/*STATUS似乎是保留字。。。*/
    CITY CHAR(10)
);

INSERT INTO S(SNO,SNAME,STATUS_,CITY)
    VALUES('S1','精益',20,'天津')
INSERT INTO S(SNO,SNAME,STATUS_,CITY)
    VALUES('S2','盛锡',10,'北京')
INSERT INTO S(SNO,SNAME,STATUS_,CITY)
    VALUES('S3','东方红',30,'北京')
INSERT INTO S(SNO,SNAME,STATUS_,CITY)
    VALUES('S4','丰泰盛',20,'天津')
INSERT INTO S(SNO,SNAME,STATUS_,CITY)
    VALUES('S5','为民',30,'上海')

CREATE TABLE P
(
    PNO CHAR(2) PRIMARY KEY,
	PNAME CHAR(10),
	COLOR CHAR(5),
	WEIGHT_ INT/*WEIGHT似乎是保留字。。。*/
);

INSERT INTO P(PNO,PNAME,COLOR,WEIGHT_)
    VALUES('P1','螺母','红',12)
INSERT INTO P(PNO,PNAME,COLOR,WEIGHT_)
    VALUES('P2','螺栓','绿',17)
INSERT INTO P(PNO,PNAME,COLOR,WEIGHT_)
    VALUES('P3','螺丝刀','蓝',14)
INSERT INTO P(PNO,PNAME,COLOR,WEIGHT_)
    VALUES('P4','螺丝刀','红',14)
INSERT INTO P(PNO,PNAME,COLOR,WEIGHT_)
    VALUES('P5','凸轮','蓝',40)
INSERT INTO P(PNO,PNAME,COLOR,WEIGHT_)
    VALUES('P6','齿轮','红',30)

CREATE TABLE J
(
    JNO CHAR(2) PRIMARY KEY,
	JNAME CHAR(10),
	CITY CHAR(10)
);

INSERT INTO J(JNO,JNAME,CITY)
    VALUES('J1','三建','北京')
INSERT INTO J(JNO,JNAME,CITY)
    VALUES('J2','一汽','长春')
INSERT INTO J(JNO,JNAME,CITY)
    VALUES('J3','弹簧厂','天津')
INSERT INTO J(JNO,JNAME,CITY)
    VALUES('J4','造船厂','天津')
INSERT INTO J(JNO,JNAME,CITY)
    VALUES('J5','机车厂','唐山')
INSERT INTO J(JNO,JNAME,CITY)
    VALUES('J6','无线电厂','常州')
INSERT INTO J(JNO,JNAME,CITY)
    VALUES('J7','半导体厂','南京')

CREATE TABLE SPJ
(
    SNO CHAR(2),
	PNO CHAR(2),
	JNO CHAR(2),
	QTY INT
);

INSERT INTO SPJ(SNO,PNO,JNO,QTY)
    VALUES('S1','P1','J1',200)
INSERT INTO SPJ(SNO,PNO,JNO,QTY)
    VALUES('S1','P1','J3',100)
INSERT INTO SPJ(SNO,PNO,JNO,QTY)
    VALUES('S1','P1','J4',700)
INSERT INTO SPJ(SNO,PNO,JNO,QTY)
    VALUES('S1','P2','J2',100)
INSERT INTO SPJ(SNO,PNO,JNO,QTY)
    VALUES('S2','P3','J1',400)
INSERT INTO SPJ(SNO,PNO,JNO,QTY)
    VALUES('S2','P3','J2',200)
INSERT INTO SPJ(SNO,PNO,JNO,QTY)
    VALUES('S2','P3','J4',500)
INSERT INTO SPJ(SNO,PNO,JNO,QTY)
    VALUES('S2','P3','J5',400)
INSERT INTO SPJ(SNO,PNO,JNO,QTY)
    VALUES('S2','P5','J1',400)
INSERT INTO SPJ(SNO,PNO,JNO,QTY)
    VALUES('S2','P5','J2',100)
INSERT INTO SPJ(SNO,PNO,JNO,QTY)
    VALUES('S3','P1','J1',200)
INSERT INTO SPJ(SNO,PNO,JNO,QTY)
    VALUES('S3','P3','J1',200)
INSERT INTO SPJ(SNO,PNO,JNO,QTY)
    VALUES('S4','P5','J1',100)
INSERT INTO SPJ(SNO,PNO,JNO,QTY)
    VALUES('S4','P6','J3',300)
INSERT INTO SPJ(SNO,PNO,JNO,QTY)
    VALUES('S4','P6','J4',200)
INSERT INTO SPJ(SNO,PNO,JNO,QTY)
    VALUES('S5','P2','J4',100)
INSERT INTO SPJ(SNO,PNO,JNO,QTY)
    VALUES('S5','P3','J1',200)
INSERT INTO SPJ(SNO,PNO,JNO,QTY)
    VALUES('S5','P6','J2',200)
INSERT INTO SPJ(SNO,PNO,JNO,QTY)
    VALUES('S5','P6','J4',500)*/

/****3.2****/
/*3.2.1*/
SELECT DISTINCT SNO
FROM SPJ
WHERE JNO='J1'

/*3.2.2*/
SELECT DISTINCT SNO
FROM SPJ
WHERE JNO='J1' AND PNO='P1'

/*3.2.3*/
SELECT SNO
FROM SPJ,P
WHERE JNO='J1' AND
      COLOR='红' AND
	  SPJ.PNO=P.PNO

/*3.2.4*/
SELECT DISTINCT JNO
FROM SPJ
WHERE JNO NOT IN
    (SELECT JNO
	 FROM SPJ,P,S
	 WHERE S.CITY='天津' AND
	       COLOR='红' AND
		   S.SNO=SPJ.SNO AND
		   P.PNO=SPJ.PNO)

/*3.2.5*/


/****3.3****/
/*3.3.1*/
SELECT SNAME,CITY
FROM S

/*3.3.2*/
SELECT PNAME,COLOR,WEIGHT_
FROM P

/*3.3.3*/
SELECT DISTINCT JNO
FROM SPJ
WHERE SNO='S1'

/*3.3.4*/
SELECT PNAME,QTY
FROM SPJ,P
WHERE SPJ.PNO=P.PNO AND
      JNO='J2'

/*3.3.5*/
SELECT DISTINCT PNO
FROM S,SPJ
WHERE CITY='上海' AND
      S.SNO=SPJ.SNO

/*3.3.6*/
SELECT DISTINCT JNAME
FROM S,J,SPJ
WHERE S.CITY='上海' AND
      S.SNO=SPJ.SNO AND
	  J.JNO=SPJ.JNO

/*3.3.7*/
SELECT DISTINCT JNO
FROM SPJ
WHERE JNO NOT IN
    (SELECT DISTINCT JNO
	 FROM SPJ,S
	 WHERE CITY='天津' AND
	       SPJ.SNO=S.SNO)

SELECT DISTINCT JNO
FROM SPJ SPJX
WHERE NOT EXISTS
    (SELECT *
	 FROM SPJ SPJY
	 WHERE SPJY.SNO='S1' AND
	       NOT EXISTS
		   (SELECT *
		    FROM SPJ SPJZ
			WHERE SPJZ.JNO=SPJX.JNO AND
			      SPJZ.PNO=SPJY.PNO))