DATAS SEGMENT
    NUM1 DB 23H,0CCH,1BH
    NUM2 DB 45H,0DDH,2BH
    NUM3 DB 00H,00H,00H 
DATAS ENDS

STACKS SEGMENT
    ;此处输入堆栈段代码
STACKS ENDS

CODES SEGMENT
    ASSUME CS:CODES,DS:DATAS,SS:STACKS
START:
    MOV AX,DATAS
    MOV DS,AX
    
    MOV AL,NUM1
    MOV AH,NUM1[1]
    ADD AX,WORD PTR NUM2
    MOV WORD PTR NUM3,AX
    
    MOV AL,NUM1[2]
    ADC AL,NUM2[2]
    MOV NUM3[2],AL
    
    MOV AH,4CH
    INT 21H
CODES ENDS
    END START