DATAS SEGMENT
    DATA DB 0FFH,00H
    MUL2 DB 00H,00H
    NUM21 DB 00H,00H  
DATAS ENDS

STACKS SEGMENT
    ;此处输入堆栈段代码
STACKS ENDS

CODES SEGMENT
    ASSUME CS:CODES,DS:DATAS,SS:STACKS
START:
    MOV AX,DATAS
    MOV DS,AX
    
    MOV AX,WORD PTR DATA
    SHL AX,2
    MOV WORD PTR MUL2,AX
    
    SHL AX,2
    
    ADD AX,WORD PTR DATA
    ADD AX,WORD PTR MUL2
    
    MOV WORD PTR NUM21,AX
    
    MOV AH,4CH
    INT 21H
CODES ENDS
    END START