DATAS SEGMENT
    DATA1 DB 01H,02H,03H,07H,08H,09H,0AH,11H,16H,20H
    ;LEN1 EQU $
    DATA2 DB 04H,05H,06H,07H,0BH,0FH,13H,21H,26H,30H
    ;LEN2 EQU $
    DATA3 DB 20 DUP(0FFH)  
DATAS ENDS

STACKS SEGMENT
    ;此处输入堆栈段代码
STACKS ENDS

CODES SEGMENT
    ASSUME CS:CODES,DS:DATAS,SS:STACKS
START:
    MOV AX,DATAS
    MOV DS,AX
    
    MOV BX,0
    MOV DI,0
    MOV SI,0
AGAIN1:
    CMP DI,0AH
    JE DATA1END
    CMP SI,0AH
    JE DATA2END
    MOV AL,BYTE PTR DATA1[DI]
    MOV CL,BYTE PTR DATA2[SI]
    CMP AL,CL
    JB MOVE1
    MOV BYTE PTR DATA3[BX],CL
    INC BX
    INC SI
    JMP AGAIN1
MOVE1:
    MOV BYTE PTR DATA3[BX],AL
    INC BX
    INC DI
    JMP AGAIN1
    
DATA1END:
    CMP SI,0AH
    JE ENDD
    MOV CL,BYTE PTR DATA2[SI]
    MOV BYTE PTR DATA3[BX],CL
    INC BX
    INC SI
    JMP DATA1END 
    
DATA2END:
    CMP DI,0AH
    JE ENDD
    MOV AL,BYTE PTR DATA1[DI]
    MOV BYTE PTR DATA3[BX],AL
    INC BX
    INC DI
    JMP DATA1END
      
ENDD:
    MOV AH,4CH
    INT 21H
CODES ENDS
    END START