DATAS SEGMENT
    DATA DB 01H,02H,03H,04H,05H,06H,07H,08H,09H,0AH
    CANNOT DB 'cannot find it',0DH,0AH,'$'
    TEN DB '10$' 
DATAS ENDS

STACKS SEGMENT
    ;此处输入堆栈段代码
STACKS ENDS

CODES SEGMENT
    ASSUME CS:CODES,DS:DATAS,SS:STACKS
START:
    MOV AX,DATAS
    MOV DS,AX
    
    MOV AX,0
    MOV BX,0
    MOV CX,9
    MOV DL,2
    
AGAIN:
    CMP BX,CX
    JA FALSE  ;IF BX>CX,WE CANNOT FIND A MIDDLE ONE
    MOV AX,BX
    ADD AX,CX
    DIV DL
    MOV AH,0
    MOV DI,AX               
    CMP BYTE PTR DATA[DI],0BH
    JE  PRINT ;FIND IT
    JA  LOW   ;WHEN LOW
    MOV BX,AX ;WHEN HIGH
    INC BX
    JMP AGAIN
LOW:
    MOV CX,AX
    DEC CX
    JMP AGAIN
    
    ;PRINT MESSAGE
PRINT:
    MOV DL,AL
    CMP DL,9
    JE PRINT10
    ADD DL,31H
    MOV AH,2
    INT 21H
    JMP ENDD
PRINT10:
    MOV DX,OFFSET TEN
    MOV AH,9
    INT 21H
    JMP ENDD
FALSE:
    MOV DX,OFFSET CANNOT
    MOV AH,9
    INT 21H
    
    
ENDD:
    MOV AH,4CH
    INT 21H
CODES ENDS
    END START