DATAS SEGMENT
     DATA1 DB 'HELLO WORLD'
     DATA2 DB 'HELLO MYSELF'
     DATA3 DB 20 DUP(01H)
     DATA4 DB 20 DUP(01H)
     DATA5 DW 1234H
     DATA6 DD 12345678H
     ;DATA7 DQ 12345678H 
DATAS ENDS

STACKS SEGMENT
    ;此处输入堆栈段代码
STACKS ENDS

CODES SEGMENT
    ASSUME CS:CODES,DS:DATAS,SS:STACKS
START:
    MOV AX,DATAS
    MOV DS,AX
    
    MOV AH,1
    MOV AL,2
    MOV BH,3
    MOV BL,4
    MOV CH,5
    MOV CL,6
    MOV DH,7
    MOV DL,8
    PUSHA
    
    MOV AL,50H
    MOV BL,0
    IDIV BL
    
    MOV AH,4CH
    INT 21H
CODES ENDS
    END START