DATAS SEGMENT
    CHUAN1 DB 'zifuChuAn$'
    CHUAN2 DB 'zIFuchuan$'
    CHUAN3 DB 'zIFuch$'
    NUM1 DB 00H
    NUM2 DB 00H
    NUM3 DB 00H
DATAS ENDS

STACKS SEGMENT
    ;此处输入堆栈段代码
STACKS ENDS

CODES SEGMENT
    ASSUME CS:CODES,DS:DATAS,SS:STACKS
START:
    MOV AX,DATAS
    MOV DS,AX
    
    MOV AX,0
    LEA SI,CHUAN1
    LEA DI,CHUAN2
    CALL STRCMP
    CMP AL,1
    JE NUM1ADD
    MOV CL,BYTE PTR NUM2
    INC CL
    MOV BYTE PTR NUM2,CL
    JMP CMP2
NUM1ADD:
    MOV CL,BYTE PTR NUM1
    INC CL
    MOV BYTE PTR NUM1,CL
    
CMP2:
    MOV AX,0
    LEA SI,CHUAN1
    LEA DI,CHUAN3
    CALL STRCMP
    CMP AL,1
    JE NUM1ADD2
    MOV CL,BYTE PTR NUM3
    INC CL
    MOV BYTE PTR NUM3,CL
    JMP CMP3
NUM1ADD2:
    MOV CL,BYTE PTR NUM1
    INC CL
    MOV BYTE PTR NUM1,CL
    
CMP3:
    MOV AX,0
    LEA SI,CHUAN2
    LEA DI,CHUAN3
    CALL STRCMP
    CMP AL,1
    JE NUM2ADD
    MOV CL,BYTE PTR NUM3
    INC CL
    MOV BYTE PTR NUM3,CL
    JMP OUTIT
NUM2ADD:
    MOV CL,BYTE PTR NUM2
    INC CL
    MOV BYTE PTR NUM2,CL
    
OUTIT:
    MOV CL,2
OUT_AGAIN:
    CMP CL,0
    JL OUT_END
    CMP CL,BYTE PTR NUM1
    JE OUT1
    CMP CL,BYTE PTR NUM2
    JE OUT2
    CMP CL,BYTE PTR NUM3
    JE OUT3

OUT1:
    LEA DX,CHUAN1
    MOV AH,9
    INT 21H
    MOV DL,0DH
    MOV AH,2
    INT 21H
    MOV DL,0AH
    MOV AH,2
    INT 21H
    DEC CL
    JMP OUT_AGAIN
    
OUT2:
    LEA DX,CHUAN2
    MOV AH,9
    INT 21H
    MOV DL,0DH
    MOV AH,2
    INT 21H
    MOV DL,0AH
    MOV AH,2
    INT 21H
    DEC CL
    JMP OUT_AGAIN
    
OUT3:
    LEA DX,CHUAN3
    MOV AH,9
    INT 21H
    MOV DL,0DH
    MOV AH,2
    INT 21H
    MOV DL,0AH
    MOV AH,2
    INT 21H
    DEC CL
    JMP OUT_AGAIN
    
OUT_END:    
    
    MOV AH,4CH
    INT 21H
    
STRCMP PROC
    PUSH BX
    MOV BX,0
AGAIN:
    CMP BYTE PTR[BX][SI],'$'
    JE ONE0
    CMP BYTE PTR[BX][DI],'$'
    JE TWO0
    
    MOV AL,BYTE PTR[BX][SI]
    CMP AL,BYTE PTR[BX][DI]
    JB ONE0
    CMP AL,BYTE PTR[BX][DI]
    JA TWO0
    INC BX
    JMP AGAIN
    
ONE0:
    MOV AL,01H
    JMP ENDD
TWO0:
    MOV AH,01H
    JMP ENDD

ENDD:               
    POP BX
    RET
ENDP

            
CODES ENDS
    END START