DATAS SEGMENT
    DATA1 DB 'ABCDEFGHIJKLMNOPQRSTUVWXYZ$'
    DATA2 DB 'abcdefghijklmnopqrstuvwxyz$'  
DATAS ENDS

STACKS SEGMENT
    ;此处输入堆栈段代码
STACKS ENDS

CODES SEGMENT
    ASSUME CS:CODES,DS:DATAS,SS:STACKS
START:
    MOV AX,DATAS
    MOV DS,AX
    
    MOV SI,0
LOOP1:
    MOV AL,DATA1[SI]
    CMP AL,'$'
    JE LOOP1_END
    OR AL,20H
    MOV BYTE PTR DATA1[SI],AL
    INC SI
    JMP LOOP1
LOOP1_END:

    MOV SI,0
LOOP2:
    MOV AL,DATA2[SI]
    CMP AL,'$'
    JE LOOP2_END
    AND AL,5FH
    MOV BYTE PTR DATA2[SI],AL
    INC SI
    JMP LOOP2
LOOP2_END:
    
    
    MOV AH,4CH
    INT 21H
CODES ENDS
    END START