DATAS SEGMENT
    DATA1 DB 'HELLO $'
    DATA2 DB 'WORLD$'
    DATA3 DB 20 DUP(0H)  
DATAS ENDS

STACKS SEGMENT
    ;此处输入堆栈段代码
STACKS ENDS

CODES SEGMENT
    ASSUME CS:CODES,DS:DATAS,SS:STACKS
START:
    MOV AX,DATAS
    MOV DS,AX
    
    MOV SI,0
    MOV DI,0
STRCAT1:
    MOV AL,DATA1[SI]
    CMP AL,'$'
    JE STRCAT1_END
    MOV BYTE PTR DATA3[DI],AL
    INC SI
    INC DI
    JMP STRCAT1
STRCAT1_END:
    
    MOV SI,0
STRCAT2:
    MOV AL,DATA2[SI]
    CMP AL,'$'
    JE STRCAT2_END
    MOV BYTE PTR DATA3[DI],AL
    INC SI
    INC DI
    JMP STRCAT2
STRCAT2_END:

    MOV BYTE PTR DATA3[DI],'$'    
    
    MOV AH,4CH
    INT 21H
CODES ENDS
    END START